import countries from "i18n-iso-countries";

const aliasToIso2: Record<string, string> = {
  D: "DE",
  A: "AT",
  B: "BE",
  F: "FR",
  UK: "GB",
};

const alpha2ToReceiverId: Record<string, string> = {
  AT: "Lager_AT_CB1",
  BE: "Lager_BE_CB1",
  BG: "Lager_BG_CB06",
  CH: "Lager_CH_CB06",
  CZ: "Lager_CZ_CB06",
  DK: "Lager_DK_CB06",
  EE: "Lager_EE_CB1",
  ES: "Lager_ES_CB06",
  FR: "Lager_FR_CB1",
  GB: "Lager_GB_CB1",
  HR: "Lager_HR_CB06",
  HU: "Lager_HU_CB06",
  IE: "Lager_IE_CB06",
  IT: "Lager_IT_CB06",
  LT: "Lager_LT_CB06",
  LU: "Lager_LU_CB1",
  MT: "Lager_MT_CB06",
  NL: "Lager_NL_CB1",
  PL: "Lager_PL_CB06",
  RO: "Lager_RO_CB1",
  SK: "Lager_SK_CB06",
  SI: "Lager_Sl_CB1",
  DE: "RetourenLager01",
};

export const normalizeAlpha3CountryCode = (input: string): string | null => {
  if (!input) return null;
  const code = input.trim().toUpperCase();

  const normalized = aliasToIso2[code] ?? code;

  if (normalized.length === 2) {
    return countries.alpha2ToAlpha3(normalized) ?? null;
  }

  return null;
};

export const normalizeAlpha2CountryCode = (input: string): string | null => {
  if (!input) return null;
  const code = input.trim().toUpperCase();

  const normalized = aliasToIso2[code] ?? code;

  return normalized;
};

export const getReceiverIdForCountry = (input: string): string | null => {
  const alpha2Code = normalizeAlpha2CountryCode(input);

  if (!alpha2Code) {
    return null;
  }

  return alpha2ToReceiverId[alpha2Code] ?? null;
};

export const countryCodes = (locale: "de" | "en") => {
  return locale === "de" ? countryCodesDe : countryCodesEn;
};

const countryCodesDe = [
  { value: "AF", label: "Afghanistan" },
  { value: "EG", label: "Ägypten" },
  { value: "AX", label: "Åland" },
  { value: "AL", label: "Albanien" },
  { value: "DZ", label: "Algerien" },
  { value: "AS", label: "Amerikanisch-Samoa" },
  { value: "VI", label: "Amerikanische Jungferninseln" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AI", label: "Anguilla" },
  { value: "AQ", label: "Antarktis" },
  { value: "AG", label: "Antigua und Barbuda" },
  { value: "GQ", label: "Äquatorialguinea" },
  { value: "AR", label: "Argentinien" },
  { value: "AM", label: "Armenien" },
  { value: "AW", label: "Aruba" },
  { value: "AZ", label: "Aserbaidschan" },
  { value: "ET", label: "Äthiopien" },
  { value: "AU", label: "Australien" },
  { value: "BS", label: "Bahamas" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesch" },
  { value: "BB", label: "Barbados" },
  { value: "BE", label: "Belgien" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BM", label: "Bermuda" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivien" },
  { value: "BA", label: "Bosnien und Herzegowina" },
  { value: "BW", label: "Botswana" },
  { value: "BV", label: "Bouvetinsel" },
  { value: "BR", label: "Brasilien" },
  { value: "VG", label: "Britische Jungferninseln" },
  { value: "IO", label: "Britisches Territorium im Indischen Ozean" },
  { value: "BN", label: "Brunei" },
  { value: "BG", label: "Bulgarien" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CK", label: "Cookinseln" },
  { value: "CR", label: "Costa Rica" },
  { value: "CW", label: "Curaçao" },
  { value: "DK", label: "Dänemark" },
  { value: "DE", label: "Deutschland" },
  { value: "DM", label: "Dominica" },
  { value: "DO", label: "Dominikanische Republik" },
  { value: "DJ", label: "Dschibuti" },
  { value: "EC", label: "Ecuador" },
  { value: "SV", label: "El Salvador" },
  { value: "CI", label: "Elfenbeinküste" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estland" },
  { value: "FK", label: "Falklandinseln" },
  { value: "FO", label: "Färöer-Inseln" },
  { value: "FJ", label: "Fidschi" },
  { value: "FI", label: "Finnland" },
  { value: "FR", label: "Frankreich" },
  { value: "GF", label: "Französisch-Guayana" },
  { value: "PF", label: "Französisch-Polynesien" },
  { value: "TF", label: "Französische Süd- und Antarktisgebiete" },
  { value: "GA", label: "Gabun" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgien" },
  { value: "GH", label: "Ghana" },
  { value: "GI", label: "Gibraltar" },
  { value: "GD", label: "Grenada" },
  { value: "GR", label: "Griechenland" },
  { value: "GL", label: "Grönland" },
  { value: "GP", label: "Guadeloupe" },
  { value: "GU", label: "Guam" },
  { value: "GT", label: "Guatemala" },
  { value: "GG", label: "Guernsey" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HM", label: "Heard und die McDonaldinseln" },
  { value: "HN", label: "Honduras" },
  { value: "HK", label: "Hongkong" },
  { value: "IN", label: "Indien" },
  { value: "ID", label: "Indonesien" },
  { value: "IM", label: "Insel Man" },
  { value: "IQ", label: "Irak" },
  { value: "IR", label: "Iran" },
  { value: "IE", label: "Irland" },
  { value: "IS", label: "Island" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italien" },
  { value: "JM", label: "Jamaika" },
  { value: "JP", label: "Japan" },
  { value: "YE", label: "Jemen" },
  { value: "JE", label: "Jersey" },
  { value: "JO", label: "Jordanien" },
  { value: "KY", label: "Kaimaninseln" },
  { value: "KH", label: "Kambodscha" },
  { value: "CM", label: "Kamerun" },
  { value: "CA", label: "Kanada" },
  { value: "CV", label: "Kap Verde" },
  { value: "BQ", label: "Karibische Niederlande" },
  { value: "KZ", label: "Kasachstan" },
  { value: "QA", label: "Katar" },
  { value: "KE", label: "Kenia" },
  { value: "KG", label: "Kirgisistan" },
  { value: "KI", label: "Kiribati" },
  { value: "UM", label: "Kleinere Inselbesitzungen der Vereinigten Staaten" },
  { value: "CC", label: "Kokosinseln" },
  { value: "CO", label: "Kolumbien" },
  { value: "KM", label: "Komoren" },
  { value: "CG", label: "Kongo" },
  { value: "CD", label: "Kongo (Dem. Rep.)" },
  { value: "XK", label: "Kosovo" },
  { value: "HR", label: "Kroatien" },
  { value: "CU", label: "Kuba" },
  { value: "KW", label: "Kuwait" },
  { value: "LA", label: "Laos" },
  { value: "LS", label: "Lesotho" },
  { value: "LV", label: "Lettland" },
  { value: "LB", label: "Libanon" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libyen" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Litauen" },
  { value: "LU", label: "Luxemburg" },
  { value: "MO", label: "Macao" },
  { value: "MG", label: "Madagaskar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "MV", label: "Malediven" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MA", label: "Marokko" },
  { value: "MH", label: "Marshallinseln" },
  { value: "MQ", label: "Martinique" },
  { value: "MR", label: "Mauretanien" },
  { value: "MU", label: "Mauritius" },
  { value: "YT", label: "Mayotte" },
  { value: "MX", label: "Mexiko" },
  { value: "FM", label: "Mikronesien" },
  { value: "MD", label: "Moldawien" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolei" },
  { value: "ME", label: "Montenegro" },
  { value: "MS", label: "Montserrat" },
  { value: "MZ", label: "Mosambik" },
  { value: "MM", label: "Myanmar" },
  { value: "NA", label: "Namibia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepal" },
  { value: "NC", label: "Neukaledonien" },
  { value: "NZ", label: "Neuseeland" },
  { value: "NI", label: "Nicaragua" },
  { value: "NL", label: "Niederlande" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "NU", label: "Niue" },
  { value: "KP", label: "Nordkorea" },
  { value: "MP", label: "Nördliche Marianen" },
  { value: "MK", label: "Nordmazedonien" },
  { value: "NF", label: "Norfolkinsel" },
  { value: "NO", label: "Norwegen" },
  { value: "OM", label: "Oman" },
  { value: "AT", label: "Österreich" },
  { value: "TL", label: "Osttimor" },
  { value: "PK", label: "Pakistan" },
  { value: "PS", label: "Palästina" },
  { value: "PW", label: "Palau" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua-Neuguinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippinen" },
  { value: "PN", label: "Pitcairninseln" },
  { value: "PL", label: "Polen" },
  { value: "PT", label: "Portugal" },
  { value: "PR", label: "Puerto Rico" },
  { value: "RE", label: "Réunion" },
  { value: "RW", label: "Ruanda" },
  { value: "RO", label: "Rumänien" },
  { value: "RU", label: "Russland" },
  { value: "BL", label: "Saint-Barthélemy" },
  { value: "MF", label: "Saint-Martin" },
  { value: "SB", label: "Salomonen" },
  { value: "ZM", label: "Sambia" },
  { value: "WS", label: "Samoa" },
  { value: "SM", label: "San Marino" },
  { value: "ST", label: "São Tomé und Príncipe" },
  { value: "SA", label: "Saudi-Arabien" },
  { value: "SE", label: "Schweden" },
  { value: "CH", label: "Schweiz" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbien" },
  { value: "SC", label: "Seychellen" },
  { value: "SL", label: "Sierra Leone" },
  { value: "ZW", label: "Simbabwe" },
  { value: "SG", label: "Singapur" },
  { value: "SX", label: "Sint Maarten" },
  { value: "SK", label: "Slowakei" },
  { value: "SI", label: "Slowenien" },
  { value: "SO", label: "Somalia" },
  { value: "ES", label: "Spanien" },
  { value: "SJ", label: "Spitzbergen und Jan Mayen" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SH", label: "St. Helena, Ascension und Tristan da Cunha" },
  { value: "KN", label: "St. Kitts und Nevis" },
  { value: "LC", label: "St. Lucia" },
  { value: "PM", label: "St. Pierre und Miquelon" },
  { value: "VC", label: "St. Vincent und die Grenadinen" },
  { value: "ZA", label: "Südafrika" },
  { value: "SD", label: "Sudan" },
  { value: "GS", label: "Südgeorgien und die Südlichen Sandwichinseln" },
  { value: "KR", label: "Südkorea" },
  { value: "SS", label: "Südsudan" },
  { value: "SR", label: "Suriname" },
  { value: "SZ", label: "Swasiland" },
  { value: "SY", label: "Syrien" },
  { value: "TJ", label: "Tadschikistan" },
  { value: "TW", label: "Taiwan" },
  { value: "TZ", label: "Tansania" },
  { value: "TH", label: "Thailand" },
  { value: "TG", label: "Togo" },
  { value: "TK", label: "Tokelau" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad und Tobago" },
  { value: "TD", label: "Tschad" },
  { value: "CZ", label: "Tschechien" },
  { value: "TN", label: "Tunesien" },
  { value: "TR", label: "Türkei" },
  { value: "TM", label: "Turkmenistan" },
  { value: "TC", label: "Turks-und Caicosinseln" },
  { value: "TV", label: "Tuvalu" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "HU", label: "Ungarn" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Usbekistan" },
  { value: "VU", label: "Vanuatu" },
  { value: "VA", label: "Vatikanstadt" },
  { value: "VE", label: "Venezuela" },
  { value: "AE", label: "Vereinigte Arabische Emirate" },
  { value: "US", label: "Vereinigte Staaten" },
  { value: "GB", label: "Vereinigtes Königreich" },
  { value: "VN", label: "Vietnam" },
  { value: "WF", label: "Wallis und Futuna" },
  { value: "CX", label: "Weihnachtsinsel" },
  { value: "BY", label: "Weißrussland" },
  { value: "EH", label: "Westsahara" },
  { value: "CF", label: "Zentralafrikanische Republik" },
  { value: "CY", label: "Zypern" },
];

const countryCodesEn = [
  { value: "AF", label: "Afghanistan" },
  { value: "EG", label: "Egypt" },
  { value: "AX", label: "Åland Islands" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AS", label: "American Samoa" },
  { value: "VI", label: "U.S. Virgin Islands" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AI", label: "Anguilla" },
  { value: "AQ", label: "Antarctica" },
  { value: "AG", label: "Antigua and Barbuda" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AW", label: "Aruba" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "ET", label: "Ethiopia" },
  { value: "AU", label: "Australia" },
  { value: "BS", label: "Bahamas" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BM", label: "Bermuda" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BV", label: "Bouvet Island" },
  { value: "BR", label: "Brazil" },
  { value: "VG", label: "British Virgin Islands" },
  { value: "IO", label: "British Indian Ocean Territory" },
  { value: "BN", label: "Brunei" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CK", label: "Cook Islands" },
  { value: "CR", label: "Costa Rica" },
  { value: "CW", label: "Curaçao" },
  { value: "DK", label: "Denmark" },
  { value: "DE", label: "Germany" },
  { value: "DM", label: "Dominica" },
  { value: "DO", label: "Dominican Republic" },
  { value: "DJ", label: "Djibouti" },
  { value: "EC", label: "Ecuador" },
  { value: "SV", label: "El Salvador" },
  { value: "CI", label: "Côte d'Ivoire" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "FK", label: "Falkland Islands" },
  { value: "FO", label: "Faroe Islands" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GF", label: "French Guiana" },
  { value: "PF", label: "French Polynesia" },
  { value: "TF", label: "French Southern and Antarctic Lands" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" },
  { value: "GH", label: "Ghana" },
  { value: "GI", label: "Gibraltar" },
  { value: "GD", label: "Grenada" },
  { value: "GR", label: "Greece" },
  { value: "GL", label: "Greenland" },
  { value: "GP", label: "Guadeloupe" },
  { value: "GU", label: "Guam" },
  { value: "GT", label: "Guatemala" },
  { value: "GG", label: "Guernsey" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HM", label: "Heard Island and McDonald Islands" },
  { value: "HN", label: "Honduras" },
  { value: "HK", label: "Hong Kong" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IM", label: "Isle of Man" },
  { value: "IQ", label: "Iraq" },
  { value: "IR", label: "Iran" },
  { value: "IE", label: "Ireland" },
  { value: "IS", label: "Iceland" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japan" },
  { value: "YE", label: "Yemen" },
  { value: "JE", label: "Jersey" },
  { value: "JO", label: "Jordan" },
  { value: "KY", label: "Cayman Islands" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "CV", label: "Cape Verde" },
  { value: "BQ", label: "Caribbean Netherlands" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "QA", label: "Qatar" },
  { value: "KE", label: "Kenya" },
  { value: "KG", label: "Kyrgyzstan" },
  { value: "KI", label: "Kiribati" },
  { value: "UM", label: "United States Minor Outlying Islands" },
  { value: "CC", label: "Cocos (Keeling) Islands" },
  { value: "CO", label: "Colombia" },
  { value: "KM", label: "Comoros" },
  { value: "CG", label: "Congo" },
  { value: "CD", label: "Congo (Dem. Rep.)" },
  { value: "XK", label: "Kosovo" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "KW", label: "Kuwait" },
  { value: "LA", label: "Laos" },
  { value: "LS", label: "Lesotho" },
  { value: "LV", label: "Latvia" },
  { value: "LB", label: "Lebanon" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MO", label: "Macau" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "MV", label: "Maldives" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MA", label: "Morocco" },
  { value: "MH", label: "Marshall Islands" },
  { value: "MQ", label: "Martinique" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "YT", label: "Mayotte" },
  { value: "MX", label: "Mexico" },
  { value: "FM", label: "Micronesia" },
  { value: "MD", label: "Moldova" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolia" },
  { value: "ME", label: "Montenegro" },
  { value: "MS", label: "Montserrat" },
  { value: "MZ", label: "Mozambique" },
  { value: "MM", label: "Myanmar" },
  { value: "NA", label: "Namibia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepal" },
  { value: "NC", label: "New Caledonia" },
  { value: "NZ", label: "New Zealand" },
  { value: "NI", label: "Nicaragua" },
  { value: "NL", label: "Netherlands" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "NU", label: "Niue" },
  { value: "KP", label: "North Korea" },
  { value: "MP", label: "Northern Mariana Islands" },
  { value: "MK", label: "North Macedonia" },
  { value: "NF", label: "Norfolk Island" },
  { value: "NO", label: "Norway" },
  { value: "OM", label: "Oman" },
  { value: "AT", label: "Austria" },
  { value: "TL", label: "Timor-Leste" },
  { value: "PK", label: "Pakistan" },
  { value: "PS", label: "Palestine" },
  { value: "PW", label: "Palau" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PN", label: "Pitcairn Islands" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "PR", label: "Puerto Rico" },
  { value: "RE", label: "Réunion" },
  { value: "RW", label: "Rwanda" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russia" },
  { value: "BL", label: "Saint Barthélemy" },
  { value: "MF", label: "Saint Martin" },
  { value: "SB", label: "Solomon Islands" },
  { value: "ZM", label: "Zambia" },
  { value: "WS", label: "Samoa" },
  { value: "SM", label: "San Marino" },
  { value: "ST", label: "São Tomé and Príncipe" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "ZW", label: "Zimbabwe" },
  { value: "SG", label: "Singapore" },
  { value: "SX", label: "Sint Maarten" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "SO", label: "Somalia" },
  { value: "ES", label: "Spain" },
  { value: "SJ", label: "Svalbard and Jan Mayen" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SH", label: "Saint Helena, Ascension and Tristan da Cunha" },
  { value: "KN", label: "Saint Kitts and Nevis" },
  { value: "LC", label: "Saint Lucia" },
  { value: "PM", label: "Saint Pierre and Miquelon" },
  { value: "VC", label: "Saint Vincent and the Grenadines" },
  { value: "ZA", label: "South Africa" },
  { value: "SD", label: "Sudan" },
  { value: "GS", label: "South Georgia and the South Sandwich Islands" },
  { value: "KR", label: "South Korea" },
  { value: "SS", label: "South Sudan" },
  { value: "SR", label: "Suriname" },
  { value: "SZ", label: "Eswatini" },
  { value: "SY", label: "Syria" },
  { value: "TJ", label: "Tajikistan" },
  { value: "TW", label: "Taiwan" },
  { value: "TZ", label: "Tanzania" },
  { value: "TH", label: "Thailand" },
  { value: "TG", label: "Togo" },
  { value: "TK", label: "Tokelau" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "TD", label: "Chad" },
  { value: "CZ", label: "Czech Republic" },
  { value: "TN", label: "Tunisia" },
  { value: "TR", label: "Turkey" },
  { value: "TM", label: "Turkmenistan" },
  { value: "TC", label: "Turks and Caicos Islands" },
  { value: "TV", label: "Tuvalu" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "HU", label: "Hungary" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "VU", label: "Vanuatu" },
  { value: "VA", label: "Vatican City" },
  { value: "VE", label: "Venezuela" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "US", label: "United States" },
  { value: "GB", label: "United Kingdom" },
  { value: "VN", label: "Vietnam" },
  { value: "WF", label: "Wallis and Futuna" },
  { value: "CX", label: "Christmas Island" },
  { value: "BY", label: "Belarus" },
  { value: "EH", label: "Western Sahara" },
  { value: "CF", label: "Central African Republic" },
  { value: "CY", label: "Cyprus" },
];
